theme: minima
title: Cant Hurt Me
author: Kingsley Benette
email: Kingsleyinsaidoo@yahoo.com
description: > The key to achieving your dreams and goals is through hardword.

# social links
twitter_username: methodjay14
github_username:  methodjay14

show_excerpts: false
