title: The Great Goal
author: Kingsley Benette
email: Kingsleyinsaidoo@yahoo.com
description: > # this is to movtivate and elivate anyone to do something great,"
dreams and goals do happen.
  

# social links
twitter_username: methodjay14
github_username:  methodjay14

show_excerpts: true # set to false to remove excerpts on the homepage
